dist:
  name: ilo5-collector
  output_path: ./dist

extensions:

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.143.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.143.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.143.0

receivers:
  - gomod: github.com/murasame29/opentelemetry-collector-ilo5-reciever/receiver/ilo5receiver v0.1.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.29.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.29.0
